management:
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/act?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: welcome1
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
  activiti:
    db-history-used: true
    history-level: audit
project:
  manifest:
    file:
      path: classpath:/default-project.json